Models/ErrorViewModel.cs
namespace EsteraApp.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/Joke.cs
namespace EsteraApp.Models
{
    public class Joke
    {
        public int Id { get; set; }
        public string Setup { get; set; }
        public string Punchline { get; set; }
    }

}

Models/Person.cs
namespace EsteraApp.Models
{
	public class Person
	{
		public int Id { get; set; }
		public string Nid { get; set; }
		public string Emer { get; set; }
		public string Mbiemer { get; set; }
		public string Atesi { get; set; }
		public string Amesi { get; set; }
		public string Gjinia { get; set; }
		public DateTime Datelindja { get; set; }
		public string Vendlindja { get; set; }
	}

}

Controllers/HomeController.cs
using EsteraApp.Data;
using EsteraApp.Models;
using EsteraApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace EsteraApp.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly JokeService _jokeService;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context, JokeService jokeService)
        {
            _logger = logger;
            _context = context;
            _jokeService = jokeService;
        }

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

        public async Task<IActionResult> GetRandomJoke()
        {
            try
            {
                var joke = await _jokeService.GetRandomJokeAsync();

                var existingJoke = _context.Jokes.FirstOrDefault(j => j.Setup == joke.Setup && j.Punchline == joke.Punchline);
                if (existingJoke == null)
                {
                    _context.Jokes.Add(joke);
                    await _context.SaveChangesAsync();
                }

                return Json(joke);
            }
            catch (Exception ex) {
                Console.WriteLine(ex.Message);
                return StatusCode(500, "An error occurred while processing your request.");
            }
        }
    }
}

Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EsteraApp.Data;
using EsteraApp.Models;
using X.PagedList;


namespace EsteraApp.Controllers
{
    public class PersonController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PersonController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Person
        public async Task<IActionResult> Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = page ?? 1;

            var persons = await _context.Persons
                                        .OrderBy(p => p.Id)
                                        .Skip((pageNumber - 1) * pageSize)
                                        .Take(pageSize)
                                        .ToListAsync();

            int totalRecords = await _context.Persons.CountAsync();
            var paginatedList = new StaticPagedList<Person>(persons, pageNumber, pageSize, totalRecords);

            return View(paginatedList);
        }

        // GET: Person/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Persons
                .FirstOrDefaultAsync(m => m.Id == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // GET: Person/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Person/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nid,Emer,Mbiemer,Atesi,Amesi,Gjinia,Datelindja,Vendlindja")] Person person)
        {
            if (ModelState.IsValid)
            {
                _context.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: Person/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Persons.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // POST: Person/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nid,Emer,Mbiemer,Atesi,Amesi,Gjinia,Datelindja,Vendlindja")] Person person)
        {
            if (id != person.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(person.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: Person/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Persons
                .FirstOrDefaultAsync(m => m.Id == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: Person/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var person = await _context.Persons.FindAsync(id);
            if (person != null)
            {
                _context.Persons.Remove(person);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonExists(int id)
        {
            return _context.Persons.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <button id="getJokeButton" class="btn btn-primary">Get a Random Joke</button>

    <div id="jokeDisplay" style="margin-top: 20px;">
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#getJokeButton').click(function () {
            $.ajax({
                url: '@Url.Action("GetRandomJoke", "Home")',
                method: 'GET',
                success: function (data) {
                    $('#jokeDisplay').html('<strong>' + data.setup + '</strong><br>' + data.punchline);
                },
                error: function () {
                    $('#jokeDisplay').html('Failed to retrieve joke.');
                }
            });
        });
    });
</script>

Views/Person/Create.cshtml
@model EsteraApp.Models.Person

@{
    ViewData["Title"] = "Create";
}

<h1>Krijo</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nid" class="control-label"></label>
                <input asp-for="Nid" class="form-control" />
                <span asp-validation-for="Nid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Emer" class="control-label"></label>
                <input asp-for="Emer" class="form-control" />
                <span asp-validation-for="Emer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mbiemer" class="control-label"></label>
                <input asp-for="Mbiemer" class="form-control" />
                <span asp-validation-for="Mbiemer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Atesi" class="control-label"></label>
                <input asp-for="Atesi" class="form-control" />
                <span asp-validation-for="Atesi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amesi" class="control-label"></label>
                <input asp-for="Amesi" class="form-control" />
                <span asp-validation-for="Amesi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gjinia" class="control-label"></label>
                <input asp-for="Gjinia" class="form-control" />
                <span asp-validation-for="Gjinia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datelindja" class="control-label"></label>
                <input asp-for="Datelindja" class="form-control" />
                <span asp-validation-for="Datelindja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vendlindja" class="control-label"></label>
                <input asp-for="Vendlindja" class="form-control" />
                <span asp-validation-for="Vendlindja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Shto" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Kthehu te Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Person/Delete.cshtml
@model EsteraApp.Models.Person

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Emer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Emer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mbiemer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mbiemer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Atesi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Atesi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amesi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amesi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gjinia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gjinia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datelindja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datelindja)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vendlindja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vendlindja)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Person/Details.cshtml
@model EsteraApp.Models.Person

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Emer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Emer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mbiemer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mbiemer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Atesi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Atesi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amesi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amesi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gjinia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gjinia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datelindja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datelindja)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vendlindja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vendlindja)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Person/Edit.cshtml
@model EsteraApp.Models.Person

@{
    ViewData["Title"] = "Edit";
}

<h1>Perditeso</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nid" class="control-label"></label>
                <input asp-for="Nid" class="form-control" />
                <span asp-validation-for="Nid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Emer" class="control-label"></label>
                <input asp-for="Emer" class="form-control" />
                <span asp-validation-for="Emer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mbiemer" class="control-label"></label>
                <input asp-for="Mbiemer" class="form-control" />
                <span asp-validation-for="Mbiemer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Atesi" class="control-label"></label>
                <input asp-for="Atesi" class="form-control" />
                <span asp-validation-for="Atesi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amesi" class="control-label"></label>
                <input asp-for="Amesi" class="form-control" />
                <span asp-validation-for="Amesi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gjinia" class="control-label"></label>
                <input asp-for="Gjinia" class="form-control" />
                <span asp-validation-for="Gjinia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datelindja" class="control-label"></label>
                <input asp-for="Datelindja" class="form-control" />
                <span asp-validation-for="Datelindja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vendlindja" class="control-label"></label>
                <input asp-for="Vendlindja" class="form-control" />
                <span asp-validation-for="Vendlindja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Perditeso" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Kthehu te Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Person/Index.cshtml
@using Microsoft.AspNetCore.Html
@using X.PagedList
@using X.PagedList.Mvc
@model IPagedList<EsteraApp.Models.Person>

<h1>Person</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Krijo element te ri</a>
</p>

<table id="personTable" class="table display">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model[0].Nid)</th>
            <th>@Html.DisplayNameFor(model => model[0].Emer)</th>
            <th>@Html.DisplayNameFor(model => model[0].Mbiemer)</th>
            <th>@Html.DisplayNameFor(model => model[0].Atesi)</th>
            <th>@Html.DisplayNameFor(model => model[0].Amesi)</th>
            <th>@Html.DisplayNameFor(model => model[0].Gjinia)</th>
            <th>@Html.DisplayNameFor(model => model[0].Datelindja)</th>
            <th>@Html.DisplayNameFor(model => model[0].Vendlindja)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Nid)</td>
                <td>@Html.DisplayFor(modelItem => item.Emer)</td>
                <td>@Html.DisplayFor(modelItem => item.Mbiemer)</td>
                <td>@Html.DisplayFor(modelItem => item.Atesi)</td>
                <td>@Html.DisplayFor(modelItem => item.Amesi)</td>
                <td>@Html.DisplayFor(modelItem => item.Gjinia)</td>
                <td>@Html.DisplayFor(modelItem => item.Datelindja)</td>
                <td>@Html.DisplayFor(modelItem => item.Vendlindja)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">
                        <i class="fas fa-pencil-alt"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EsteraApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EsteraApp.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EsteraApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Person</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EsteraApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>